services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev

  backend:
    build:
      context: ./frontend/backend
    ports:
      - "3001:3001"
    volumes:
      - .fronte/backend:/app
    command: npm run start
    environment:
      - NODE_ENV=production
